example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import *

app_name = 'wishlist'

urlpatterns = [
    #Lab 1
    path('', show_wishlist, name='show_wishlist'),
    #Lab 2
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    #Lab 3
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    #Lab 5
    path('ajax/', show_ajax, name="show_ajax"),
    path('ajax/submit', submit_wishlist, name="submit_wishlist")
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.contrib.auth.models import User
from django.db import models
from django import forms

# Create your models here.
class BarangWishlist(models.Model):
    user = models.ForeignKey(
                User,
                models.SET_NULL,
                blank=True,
                null=True
            )
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

class AddWishlistForm(forms.ModelForm):
    class Meta:
        model = BarangWishlist
        fields = ('nama_barang', 'harga_barang', 'deskripsi')
        widgets = {
            'deskripsi': forms.Textarea(),
        }

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
import datetime
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.core import serializers
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from wishlist.models import AddWishlistForm, BarangWishlist

# Create your views here.
# Lab 1
@login_required(login_url='/wishlist/login/') # addition in Lab 3
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    user_name = request.user.username
    context = {
        'list_barang': data_barang_wishlist,
        'nama': user_name,
        'last_login' : request.COOKIES['last_login']
    }
    return render(request, "wishlist.html", context)

#Lab 2
def show_xml(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data_barang_wishlist), 
                        content_type="application/xml")

def show_json(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data_barang_wishlist), 
                        content_type="application/json")

def show_xml_by_id(request,id):
    data_barang_by_id = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data_barang_by_id), 
                        content_type="application/xml")

def show_json_by_id(request,id):
    data_barang_by_id = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data_barang_by_id), 
                        content_type="application/json")

#Lab 3
def register(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        # mengecek apakah form sesuai kriteria
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        # mengecek di form apakah user terdaftar
        if user is not None:
            login(request, user) # melakukan login
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
#            return redirect()
            return response # mengembalikan response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login') # deleting cookie
    return redirect('wishlist:login')

# Lab 5
@login_required(login_url='/wishlist/login/')
def show_ajax(request):
    # tampilin barang
    data_barang_wishlist = BarangWishlist.objects.all()
    user_name = request.user.username    
    context = {
        'list_barang': data_barang_wishlist,
        'nama': user_name,
        'last_login' : request.COOKIES['last_login'],
    }
    return render(request, "wishlist_ajax.html", context)

@login_required(login_url='/wishlist/login/')
def submit_wishlist(request):
    # input form
    form = AddWishlistForm()
    if(request.method == 'POST'):
        get_user = request.user
        get_nama = request.POST.get('nama_barang')
        get_harga = request.POST.get('harga_barang')
        get_deskripsi = request.POST.get('deskripsi')
        
        new_wishlist = BarangWishlist(
            user = get_user,
            nama_barang = get_nama,
            harga_barang = get_harga,
            deskripsi = get_deskripsi
        )
        
        new_wishlist.save()
    return render(request, "wishlist_ajax.html")

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"/>
</head>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "container-md" c">

    <h1 style="text-align: center">Login</h1>
    <form method="POST" action="">
        {% csrf_token %}
            <div class="form-group">
                <label style="padding-top: 10px">Username</label>
                <input type="text" name="username" placeholder="Username" class="form-control">
            </div>
                    
            <div class="form-group">
                <label style="padding-top: 10px">Password</label>
                <input type="password" name="password" placeholder="Password" class="form-control">
            </div>

            <div style="text-align:center">
            <button class="btn btn-primary" type="submit" style="margin-top: 10px"> Login </button>
            </div>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
</div>
<div style="padding-top: 30px; text-align:center">
    Belum mempunyai akun? <a class="btn btn-outline-secondary btn-sm" href="{% url 'wishlist:register' %}" role="button">Buat Akun</a>
</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "register" style="padding: 50px 30px">
    
    <h1 style="text-align:center; padding:2px">Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table style="width:100%; margin:20px">  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}
<nav class="navbar bg-light">
    <div class="container-fluid">
        <p class="bi bi-person" style="margin: 1px"> {{nama}}</p>
        <a href="{% url 'wishlist:logout' %}" class="btn btn-dark">Logout</a>
    </div>
</nav>

<div>
    <h1 style="text-align:center; margin-top:25px">Welcome! </h1>
        <table class="table table-striped table-bordered" style="width:90%; margin:auto">
            <thead class="thead-dark">
                <tr>
                    <th>Nama Barang</th>
                    <th>Harga Barang</th>
                    <th>Deskripsi</th>
                </tr>
            </thead>
            {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
            <tbody>
                {% for barang in list_barang %}
                    <tr>
                        <td>{{barang.nama_barang}}</td>
                        <td>{{barang.harga_barang}}</td>
                        <td>{{barang.deskripsi}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
</div>

<div style="text-align:center">
    {% comment %} cookie {% endcomment %}
    <small>Sesi terakhir login: {{ last_login }}</small>
</div>

{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}

{% block meta %}
{% endblock meta %}

{% block content %}
<nav class="navbar bg-light">
    <div class="container-fluid">
        <p class="bi bi-person" style="margin: 1px"> {{nama}}</p>
        <a href="{% url 'wishlist:logout' %}" class="btn btn-dark">Logout</a>
    </div>
</nav>

<div class="show-wishlist">
    <h1 style="text-align:center; margin-top:25px">Welcome! </h1>
      <table class="table table-striped table-bordered" style="width:90%; margin:auto">
        <thead class="thead-dark">
          <tr>
              <th>Nama Barang</th>
              <th>Harga Barang</th>
              <th>Deskripsi</th>
          </tr>
        </thead>
        {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
        <tbody>
            {% for barang in list_barang %}
              <tr>
                  <td>{{barang.nama_barang}}</td>
                  <td>{{barang.harga_barang}}</td>
                  <td>{{barang.deskripsi}}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
</div>

<div class = "add-wishlist" style="width: 600px; margin: 40px">
    <h1 style="text-align:center;">Add Your Wishlist</h1>  

    <form method="POST" id="submit_wishlist">  
      {% csrf_token %}
      <div class="form-group">
        <label>Nama Barang</label>
        <input type="text" name="nama_barang" class="form-control" required>
      </div>

      <div class="form-group">
        <label>Harga Barang</label>
        <input rows="10" cols="70" name="harga_barang" class="form-control" required></input>
      </div>

      <div class="form-group">
        <label>Deskripsi</label>
        <textarea rows="10" cols="70" name="deskripsi" class="form-control" required></textarea>
      </div>

      <div style="text-align:center">
        <button class="btn btn-dark" type="submit" style="margin-top: 10px"> Add Wishlist </button>
      </div>
    </form>

    {% if messages %}  
        {% for message in messages %}  
            <small>{{ message }}</small>  
        {% endfor %}
    {% endif %}
</div>

<div style="text-align:center">
    {% comment %} cookie {% endcomment %}
    <small>Sesi terakhir login: {{ last_login }}</small>
</div>

<script type="text/javascript">
  $(document).on('submit', '#submit_wishlist', function(e) {
    e.preventDefault();
    $.ajax({
      type:"POST",
      url:"{% url 'wishlist:submit_wishlist' %}",
      data:{
        nama_barang:$("#nama_barang").val(),
        harga_barang:$("#harga_barang").val(),
        deskripsi:$("#deskripsi").val(),
        csrfmiddlewaretoken:'{{ csrf_token }}',
      },
      dataType: 'json',
      success: function(response) {
        alert("wishlist added!");
        window.location.reload();
      },

    });
  });

</script>
{% endblock content %}